spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/dev?serverTimezone=Asia/Seoul
      username: '{cipher}534d0fdd4dba47b6ff4f0c60040e840980213837fee608e6344ed8dec271743c'
      password: '{cipher}AQBxIShcfF0wNE59G0EXNeT5gqqLSz0+9sGakd6585/E9DL8sVJQIB3pv2Jl9s7B+bpT0ec7zy+I1tB8PiQn4AhWGk6m7+6EIU/gjGWiAUOwH0w1U4hcK9YEB4mm6aazHf1teZkO8tMao+SjUZrBp25/TXv78Y5FsicGQdfX2cvgFsxoGJiDdBQuvLSyrmPB7r9MvPTazsRCOk+nAYrALpmZMRNnjZt21/ktcmoWcTtfmF2x1ItCa5COi0xxMQCCPakISNSD/pOlLy8xLuiA4umr8b09OzpeXS2rs1USjUBnJnD2QYbBTkl8JPh3ouXw8IYC52d8SVsdMg6EDdpVoNXTonqxp/iVSVidT/k1w19AGuLZx4vLaLj56MMIE99Oc6k='
      driver-class-name: com.mysql.jdbc.Driver
token:
  expiration_time: 86400000
  secret: userServiceToken!@!_dev
  
gateway:
  ip: 192.168.19.235
