spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/dev?serverTimezone=Asia/Seoul
      username: '{cipher}AQB3XU06gJTdWPjhyr/KBrOnT6gbbaV1ebNukRZv1RKzFMy/yQZ1jc+ibfmd286NYSKfdVZoY0KfJbxCQ+r20p82xGeT1SEDQxlLKkMYwIjPcNKsoklK7jB28ZHO3vjY5gB5xBfhd712RjT3jcUwV07rB2ud/QlsPOabSVxzgDxbXA4EGXrNnraKk8utJkvkgzkbKhhB4wJ6P5eYF9GtDtKtaLH0yhzkR1EeKzq8rseus2a4MHN2+NqCSZwmcis20h7MeWX+Wo1m0ufSR1gTolbBx5l9esZxzQNy1hQ1uSHC16/XEIgFkQG/p8gf4TXAPzAoUEjXhNX7TaPDfOvg6D4NmQ0r2kIFssscm9dwCfqhheo8J7PdyQsvQ2R9DRD2JwU='
      password: '{cipher}AQBrTrJMIe7judUgf2kfaEK3kEUdoXq5wjSsFLFLx+dzRsxC8eWCVDhFu93rDwEVbqeC84TPi7++BdvPDL3iymF7J8x7gEx9hHcsZPiGfqOcW0LkBxEva0jyXwtFRRPi7F0JyVrmiYorUwJCdKTtv6bTEH8nZgYg7w8mqkVvK5rLhj0FEJnHUnMM1I+hyH9YrNQEZzxoZD22XzqOEoYJUOKSZTp8IoE5qu41q+huKPilqXopL6BaKj+4I/2vRWDAAwibEChsShmoOctatze/0cmWxBUQM0YPpzwpyPNKB5OJ1KRK2J0Ri30hprEoV/e2DCzJEMG7yiC/reAuNrvBN+DHbm4QR3ScUmSVUpl4lqYHpOVcSTpffXCkT0hhANmOUGI='
      driver-class-name: com.mysql.jdbc.Driver
token:
  expiration_time: 86400000 #userServiceToken!@!_dev
  secret: '{cipher}AQAR8QyR5llRmyldoZEvnTawVdeYRjsB+MO2r888j+/FoMpGPGKtRfSId33HV9gJLa+IeqNyWDUyS46z7U9LbgCkEkkaA6Sbss4aKc5EkHkUESRc3kEhxJ4ZQrw6e/pDUnG1JyjlICFQa3xQf3ta7bxlfJsDTaxAsS5DFQjxOByWQOpyo/U+W1eb7UIDqe8S1jsg0gen1VDFgTwmKMCrC3deRW8SQLyxshqJDzewVKLFzqsJ7e9fuMhRq5N3U6e82xLy5xEZ4jfOyqUQvLR42OkuxGD5NQQPDR7fUJC+al/kzHH2LSrVuizUBMpBKe93p3vxXs2tsSVmarlQszF2Pl3arBaCAGtqVks2E6ITGXOKh/qfbrpDj9yRSC4Jhg03FbrilaPR9sEAmneoHIAtYNN8'
  
gateway:
  ip: 192.168.19.235

order-service:
  url: http://order-service/order-service/%s/orders