spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/dev?serverTimezone=Asia/Seoul
      username: '{cipher}AQBvDlingpEcyJGrqS0qvW1CU82GF966KKHNRhBv3nSiE95EkyND7be6373EzTWOYWVrWt/sELz5h6sEApyT0lJvRnuWL9LoOSSi4mPmAryrIwpkJTbGKRIKlg91/jJ0aMOymCcD2/39WOE9RJHl39+ZL92/XZzzwZ0U7LPN+56jyBH4Ebdpo2WHCG3MiUG1yCBYAVvhIkIJa3jZ/MTxOH4V5ayvFHsARfC9ICEDh7k4u11I41sWJAMpdNfZ7x0LA+tDcTT0KJzYN1XU11jA6sOqm+rdBt3hvQeOiyqWYtRMWorlpWDYyKajvw9CwK1WnMvSGxPeJ1BMsrTTkvkiz354PBOBO8HcrdC3efqBNZEpVQTP//rJH4F78a10Q9rv4gA='
      password: '{cipher}AQAfcuVS7qCZyhsFMCwYd11Dx+Exb2ZoRSbZ0Kf/YTJt9z6ejtOcbKUKpdff7sbQUWygOktuG3KsWl44pkkRRvc/9IyBnBDOUXyDkwZNzOoM543r6FhwKG1fRU19FJNyyEQzJX+n5lts9p0bYGjyEpZ3scfvJs8fwq6iaMkOucieuVRyweHLtxu0QlprNDlakgHLj0X1GdBILKq+E6GQIvJTA+9vUwa/FjZTqOEx0+QJSfv88Dlp1JY2m89VwzbqRtuVVaOs1r9k/CPD4m6cOXsLHUqcz9aKnJCkXEFi4rVDTp1SxxqpXAEoWr/mN4UHkpnJUMbP1v3+6hCpOBsRTFT/djJMXOmGWDL7lgnrKJhjkIOBNycVnXMxkl/N8gPDiC8='
      driver-class-name: com.mysql.jdbc.Driver
token:
  expiration_time: 86400000 #userServiceToken!@!_dev
  secret: '{cipher}AQAR8QyR5llRmyldoZEvnTawVdeYRjsB+MO2r888j+/FoMpGPGKtRfSId33HV9gJLa+IeqNyWDUyS46z7U9LbgCkEkkaA6Sbss4aKc5EkHkUESRc3kEhxJ4ZQrw6e/pDUnG1JyjlICFQa3xQf3ta7bxlfJsDTaxAsS5DFQjxOByWQOpyo/U+W1eb7UIDqe8S1jsg0gen1VDFgTwmKMCrC3deRW8SQLyxshqJDzewVKLFzqsJ7e9fuMhRq5N3U6e82xLy5xEZ4jfOyqUQvLR42OkuxGD5NQQPDR7fUJC+al/kzHH2LSrVuizUBMpBKe93p3vxXs2tsSVmarlQszF2Pl3arBaCAGtqVks2E6ITGXOKh/qfbrpDj9yRSC4Jhg03FbrilaPR9sEAmneoHIAtYNN8'
  
gateway:
  ip: 192.168.19.235

order-service:
  url: http://127.0.0.1:8000/order-service/%s/orders